#!/usr/bin/env bash
#Creating a script that uses case statements
count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
        4) echo "bad luck from China";;
        9) echo "badluck from Japan";;
        17) echo "bad luck  from Italy";;
	*) echo "";;
    esac
    ((count++))
done
